[common]
# Prefix for store all internal carbon-clickhouse graphs. Supported macroses: {host}
metric-prefix = "carbon-clickhouse-old.{host}"
# Endpoint for store internal carbon metrics. Valid values: "" or "local", "tcp://host:port", "udp://host:port"
metric-endpoint = "local"
# Interval of storing internal metrics. Like CARBON_METRIC_INTERVAL
metric-interval = "1m0s"
# GOMAXPROCS
max-cpu = 2

[logging]
# "stderr", "stdout" can be used as file name
file = "stdout"
# Logging error level. Valid values: "debug", "info", "warn" "error"
level = "warn"

[data]
# Folder for buffering received data
path = "/tmp/"
# Rotate (and upload) file interval.
# Minimize chunk-interval for minimize lag between point receive and store
chunk-interval = "1s"
# Auto-increase chunk interval if the number of unprocessed files is grown
# Sample, set chunk interval to 10 if unhandled files count >= 5 and set to 60s if unhandled files count >= 20:
# chunk-auto-interval = "5:10s,20:60s"
chunk-auto-interval = "5:10s,20:60s"

[upload.graphite]
type = "points"
table = "graphite_old.graphite"
threads = 2
url = "http://clickhouse:8123/"
timeout = "1m0s"

[upload.graphite_tree]
type = "tree"
table = "graphite_old.graphite_tree"
# NOTE - vv not sure what this does vv
date = "2016-11-01"
threads = 2
url = "http://clickhouse:8123/"
timeout = "1m0s"
cache-ttl = "12h0m0s"

[tcp]
listen = "0.0.0.0:2103"
enabled = true
drop-future = "0s"
drop-past = "0s"
